[package]
name = "twenty_forty_eight"
version = "0.1.0"
authors = ["billthemaxster"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[dev-dependencies]
rstest = "0.6.4"
